//This is a configuration file generated by t_gen on 2018-05-11
#pragma once

#ifndef T_SPECS
#define T_SPECS

#define T_QT 1

#ifdef _WIN32
#define T_WIN32 1
#else
#define T_DARWIN 1
#endif

#define t_cast static_cast
#define ptr_cast dynamic_cast

#define T_CLI 1
#define App QCoreApplication

#define PROJECT ("Mere Interpreter")
#define VERSION ("v0.1")
#define AUTHOR ("TheOakCode")
#define EMAIL ("theoaktree1040@gmail.com")
#define DESCRIPTION ("An interpreter for the scripting language Mere.")
#define BUILD ("7-d (180520)")

#endif // T_SPECS
